### PR TITLE
Add intro and upload tutorials

### PR DESCRIPTION
**Pull request by jyu00**
This PR adds the introduction and "upload a program" tutorials.

The `pprint_programs()` method output is still missing but that requires metadata from other programs.

### CODE REVIEW

**Comment by ismaelfaro** [comment]
I did some changes in the Jupyters: #4

**Comment by nonhermitian** [comment]
We should make sure that tutorials start with `00` and `01` not `0` or `1` so that we can `glob` the directories easily.

**Comment by jyu00** [comment]
@nonhermitian I was only going to number the introductory tutorials and not all of them. Would that be an issue?

**Comment by nonhermitian** [comment]
If we ever have more than 10 and want a specific order than yes.  Otherwise one has to add items in order by hand to get around glob thinking 10 goes before 2 (rather than 02).

**Comment by jyu00** [comment]
ok, I wasn't going to number the rest (vqe, qka etc) because they don't need to be in order. Sounds like we'll be fine as long as the ones that _do_ need to be in order have 2-digits.

**Comment by nonhermitian** [comment]
Yeah, that was the message I was trying to get across.

**Comment by jyu00** [comment]
Going to merge this now. Will update the `pprint_programs()` output once it becomes available.

**Pull request merged**
