### PR TITLE
Add a tutorial for the VQE script and ``VQEProgram``

### PR DESCRIPTION
**Pull request by Cryoris**
### Summary

Add the VQE tutorial.

This PR is based on #9, but I split the tutorial off so the PRs are easier to review. 🙂 

I probably have to add a number for the tutorial, but didn't know whether it should be `01_vqe` or `03_vqe` (or something different).

### CODE REVIEW

**Comment by jyu00** [comment]
A couple of comments on the tutorial:

1. Can you add the link to the LiH tutorial like we discussed earlier? Something along the lines of `you can find tutorials on solving more comprehensive problems, such as lithium hydride simulation, using vqe at qiskit-nature (link)`
2. The last cell is missing its output. Alternatively you can just delete that cell if the output is not interesting with only a few iterations.

**Comment by jyu00** [comment]
@Cryoris I think a link to the general folder would be fine, especially since there are other tutorials that use VQE in that directory. 

And it looks like you'll need to rebase this PR now that #9 is merged :)

**Comment by Cryoris** [comment]
@jyu00 I added the link to nature and executed the last notebook cell. 👍🏻

**Review by jyu00 — APPROVED** [review]
Looks great. Thank you!!

**Pull request merged**
